server:
  port: 8098

kafka:
  bootstrap-servers: 127.0.0.1:9092
  mode: 'PLAINTEXT'
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      send-message-topic: message-topic